**The Basics of NumPy Arrays**




In [87]:
import numpy as np

In [88]:
np.random.seed(0)

In [89]:
x1 = np.random.randint(10, size=6) 
print("x1 ndim: ", x1.ndim)


x1 ndim:  1


In [90]:
x2 = np.random.randint(10, size=(3, 4, )) 
print("x2 size: ", x2.size)

x2 size:  12


In [92]:
print("dtype:", x2.dtype)

dtype: int64


In [93]:
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x2.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 96 bytes


In [94]:
x1

array([5, 0, 3, 3, 7, 9])

In [95]:
x1[0]

5

In [96]:

x1[4]

7

In [97]:
x1[-2]

7

In [98]:
x1[3]

3

In [24]:
x2

array([[0, 4, 3, 9],
       [0, 4, 0, 8],
       [7, 6, 8, 5]])

In [25]:
x2[2, -1]

5

In [26]:
x2[0, 0] = 12
x2

array([[12,  4,  3,  9],
       [ 0,  4,  0,  8],
       [ 7,  6,  8,  5]])

In [27]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
x[:5]

array([0, 1, 2, 3, 4])

In [29]:
x[5:]

array([5, 6, 7, 8, 9])

In [30]:
x[4:7]

array([4, 5, 6])

In [42]:
x[:5:4]

array([0, 4])

In [31]:
x[1::2]

array([1, 3, 5, 7, 9])

In [32]:
x[5::-2] 

array([5, 3, 1])

In [43]:
x[3::-1]

array([3, 2, 1, 0])

In [33]:
x2

array([[12,  4,  3,  9],
       [ 0,  4,  0,  8],
       [ 7,  6,  8,  5]])

In [34]:
x2[:2, :3] 

array([[12,  4,  3],
       [ 0,  4,  0]])

In [35]:
x2[:3, ::2]

array([[12,  3],
       [ 0,  0],
       [ 7,  8]])

In [36]:
x2[::-1, ::-1]

array([[ 5,  8,  6,  7],
       [ 8,  0,  4,  0],
       [ 9,  3,  4, 12]])

In [44]:
x2[3::-1, ::-3]

array([[ 5,  7],
       [ 8,  0],
       [ 9, 99]])

In [37]:
print(x2[0, :])

[12  4  3  9]


In [45]:
print(x2[0])

[99  4  3  9]


In [38]:
print(x2)

[[12  4  3  9]
 [ 0  4  0  8]
 [ 7  6  8  5]]


In [39]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  4]
 [ 0  4]]


In [46]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  4]
 [ 0  4]]


In [47]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  4]
 [ 0  4]]


In [48]:
print(x2)

[[99  4  3  9]
 [ 0  4  0  8]
 [ 7  6  8  5]]


In [41]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
x = np.array([1, 2, 3])

In [52]:
x.reshape((1, 3))


array([[1, 2, 3]])

In [53]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [54]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [61]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [62]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [63]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [64]:
np.concatenate([grid, grid], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
x = np.array([1, 2, 3])
grid = np.array([[4, 5, 6],
                 [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [6, 5, 4]])

In [67]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 4,  5,  6, 99],
       [ 6,  5,  4, 99]])

In [68]:
y = np.array([[100],
              [99]])
np.hstack([grid, y])

array([[  4,   5,   6, 100],
       [  6,   5,   4,  99]])

In [69]:
y = np.array([[1,2],
              [7,8]])
np.hstack([grid, y])

array([[4, 5, 6, 1, 2],
       [6, 5, 4, 7, 8]])

In [70]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [71]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [77]:
upper, lower = np.vsplit(grid, [5])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[]


In [78]:
upper, lower = np.vsplit(grid, [10])
print(upper)
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[]


In [79]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [80]:
left, right = np.hsplit(grid, [5])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[]


In [81]:
left, right = np.hsplit(grid, [10])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[]


**Aggregations: Min, Max, and Everything In Between**

In [2]:
import numpy as np

In [4]:
a = np.random.random(100)
sum(a)

52.327875349993995

In [5]:
np.sum(a)

52.32787534999399

In [7]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

10 loops, best of 5: 166 ms per loop
1000 loops, best of 5: 365 µs per loop


In [8]:
min(big_array), max(big_array)

(6.683154463171803e-08, 0.9999971545747485)

In [9]:
np.min(big_array), np.max(big_array)

(6.683154463171803e-08, 0.9999971545747485)

In [11]:
M = np.random.random((3, 5))
print(M)

[[0.06470505 0.31184953 0.45825472 0.69605038 0.96146417]
 [0.27886552 0.41383108 0.37118882 0.11924071 0.61502044]
 [0.32180035 0.48617694 0.11866029 0.56972633 0.43773535]]


In [12]:
M.sum()

6.224569657079467

In [16]:
M.min(axis=0)

array([0.06470505, 0.31184953, 0.11866029, 0.11924071, 0.43773535])

In [15]:
M.max(axis=1)

array([0.96146417, 0.61502044, 0.56972633])